title: "Joseph Edoh"
email: Josephedoh77@gmail com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://JoE11-y.github.io" 
twitter_username: Joe_Edoh
github_username:  JoeEdoh

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
